AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Creates IAM Users, Groups, and a temporary password in Secrets Manager
  for a lab on automated IAM resource provisioning.

Resources:
  UserPasswordSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Description: 'Temporary password for IAM users'
      GenerateSecretString:
        PasswordLength: 16
        ExcludePunctuation: true

  EC2UserGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: EC2Group
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess'
        - 'arn:aws:iam::aws:policy/IAMUserChangePassword'



  S3UserGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: S3Group
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess'
        - 'arn:aws:iam::aws:policy/IAMUserChangePassword'



  EC2User:
    Type: 'AWS::IAM::User'
    DependsOn:
      - UserPasswordSecret
      - EC2UserGroup
    Properties:
      UserName: ec2-user
      Groups:
        - !Ref EC2UserGroup
      LoginProfile:
        Password: !Sub '{{resolve:secretsmanager:${UserPasswordSecret}}}'
        PasswordResetRequired: true

  S3User:
    Type: 'AWS::IAM::User'
    DependsOn:
      - UserPasswordSecret
      - S3UserGroup
    Properties:
      UserName: s3-user
      Groups:
        - !Ref S3UserGroup
      LoginProfile:
        Password: !Sub '{{resolve:secretsmanager:${UserPasswordSecret}}}'
        PasswordResetRequired: true


